-- Native SQLite Schema for Aethrium War (TFS 1.8)
-- Generated to ensure compatibility with SQLite 3

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(32) NOT NULL UNIQUE,
  `password` CHAR(40) NOT NULL,
  `type` INTEGER NOT NULL DEFAULT 1,
  `premdays` INTEGER NOT NULL DEFAULT 0,
  `lastday` INTEGER NOT NULL DEFAULT 0,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `creation` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `players` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `group_id` INTEGER NOT NULL DEFAULT 1,
  `account_id` INTEGER NOT NULL,
  `level` INTEGER NOT NULL DEFAULT 1,
  `vocation` INTEGER NOT NULL DEFAULT 0,
  `health` INTEGER NOT NULL DEFAULT 150,
  `healthmax` INTEGER NOT NULL DEFAULT 150,
  `experience` INTEGER NOT NULL DEFAULT 0,
  `lookbody` INTEGER NOT NULL DEFAULT 0,
  `lookfeet` INTEGER NOT NULL DEFAULT 0,
  `lookhead` INTEGER NOT NULL DEFAULT 0,
  `looklegs` INTEGER NOT NULL DEFAULT 0,
  `looktype` INTEGER NOT NULL DEFAULT 128,
  `lookaddons` INTEGER NOT NULL DEFAULT 0,
  `maglevel` INTEGER NOT NULL DEFAULT 0,
  `mana` INTEGER NOT NULL DEFAULT 0,
  `manamax` INTEGER NOT NULL DEFAULT 0,
  `manaspent` INTEGER NOT NULL DEFAULT 0,
  `soul` INTEGER NOT NULL DEFAULT 0,
  `town_id` INTEGER NOT NULL DEFAULT 1,
  `posx` INTEGER NOT NULL DEFAULT 0,
  `posy` INTEGER NOT NULL DEFAULT 0,
  `posz` INTEGER NOT NULL DEFAULT 0,
  `cap` INTEGER NOT NULL DEFAULT 400,
  `sex` INTEGER NOT NULL DEFAULT 0,
  `lastlogin` INTEGER NOT NULL DEFAULT 0,
  `lastip` INTEGER NOT NULL DEFAULT 0,
  `save` INTEGER NOT NULL DEFAULT 1,
  `skull` INTEGER NOT NULL DEFAULT 0,
  `skulltime` INTEGER NOT NULL DEFAULT 0,
  `rank_id` INTEGER NOT NULL DEFAULT 0,
  `guild_id` INTEGER NOT NULL DEFAULT 0,
  `skill_fist` INTEGER NOT NULL DEFAULT 10,
  `skill_club` INTEGER NOT NULL DEFAULT 10,
  `skill_sword` INTEGER NOT NULL DEFAULT 10,
  `skill_axe` INTEGER NOT NULL DEFAULT 10,
  `skill_dist` INTEGER NOT NULL DEFAULT 10,
  `skill_shielding` INTEGER NOT NULL DEFAULT 10,
  `skill_fishing` INTEGER NOT NULL DEFAULT 10,
  FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `guilds` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `ownerid` INTEGER NOT NULL UNIQUE,
  `creationdata` INTEGER NOT NULL,
  `motd` VARCHAR(255) NOT NULL DEFAULT '',
  FOREIGN KEY (`ownerid`) REFERENCES `players` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `guild_ranks` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `guild_id` INTEGER NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `level` INTEGER NOT NULL,
  FOREIGN KEY (`guild_id`) REFERENCES `guilds` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `guild_membership` (
  `player_id` INTEGER PRIMARY KEY,
  `guild_id` INTEGER NOT NULL,
  `rank_id` INTEGER NOT NULL,
  `nick` VARCHAR(15) NOT NULL DEFAULT '',
  FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`guild_id`) REFERENCES `guilds` (`id`) ON DELETE CASCADE,
  FOREIGN KEY (`rank_id`) REFERENCES `guild_ranks` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `towns` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `posx` INTEGER NOT NULL DEFAULT 0,
  `posy` INTEGER NOT NULL DEFAULT 0,
  `posz` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `war_scores` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `guild_id` INTEGER NOT NULL,
  `frags` INTEGER NOT NULL DEFAULT 0,
  `round_id` INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (`guild_id`) REFERENCES `guilds` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `server_config` (
  `config` VARCHAR(50) PRIMARY KEY,
  `value` VARCHAR(256) NOT NULL DEFAULT ''
);

INSERT OR REPLACE INTO `server_config` (`config`, `value`) VALUES ('db_version', '29');
